In [5]:
import sklearn

In [6]:
import pandas as pd

In [8]:
#Preprocess english.csv
e1=pd.read_csv('english1.csv')

In [10]:
e1.head()

Unnamed: 0                                                  0  new_index
0          37  in  johnson was awarded an american institute ...          0
1          40  bussy-saint-georges has built its identity on ...          1
2          76  minnesotas state parks are spread across the s...          2
3          90  nordahl road is a station served by north coun...          3
4          97  a talk by takis fotopoulos about the internati...          4

In [12]:
e2=e1.drop('Unnamed: 0', axis=1)

In [13]:
e2.head()

0  new_index
0  in  johnson was awarded an american institute ...          0
1  bussy-saint-georges has built its identity on ...          1
2  minnesotas state parks are spread across the s...          2
3  nordahl road is a station served by north coun...          3
4  a talk by takis fotopoulos about the internati...          4

In [14]:
import string

for char in string.punctuation:
    print(char, end=' ')

! " # $ % & ' ( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~ 

In [15]:
pun_dic = dict((ord(char),None) for char in string.punctuation)

In [16]:
pun_dic

{33: None,
 34: None,
 35: None,
 36: None,
 37: None,
 38: None,
 39: None,
 40: None,
 41: None,
 42: None,
 43: None,
 44: None,
 45: None,
 46: None,
 47: None,
 58: None,
 59: None,
 60: None,
 61: None,
 62: None,
 63: None,
 64: None,
 91: None,
 92: None,
 93: None,
 94: None,
 95: None,
 96: None,
 123: None,
 124: None,
 125: None,
 126: None}

In [17]:
e2.isna().sum()

0            0
new_index    0
dtype: int64

In [18]:
e3=e1.dropna()

In [19]:
e3.shape

(3225, 3)

In [ ]:
e2.shape

(2225, 1)

In [20]:
data_eng =[]
lang_eng =[]

In [22]:
import re
for i,line in e3.iterrows():
    line = line['0']
    if len(line)!=0:
        line = line.lower()                  #Convert everything to lowercase
        line = re.sub(r"\d+", "", line)      # remove all digits
        line = line.translate(pun_dic)       #Replace all punctuators with None
        data_eng.append(line)                #Add the processed tokenized data to list
        lang_eng.append("English")      
        

In [23]:
len(lang_eng)

3225

In [24]:
data_eng[2224]

' the conservatives campaign director has denied a report claiming he warned michael howard the party could not win the next general election  the times on monday said australian lynton crosby told the party leader to focus on trying to increase the tories commons presence by  to  seats but mr crosby said in a statement i have never had any such conversation and i do not hold that view mr howard later added there was not one iota of truth in the report the strategist helped australias pm john howard win four elections mr howard appointed mr crosby as his elections chief last october mr crosbys statement said the conservative party has been making an impact on the issues of lower tax and controlled immigration over the past week it added the labour party will be wanting to do all they can to distract attention away from the issues that really matter to people '

In [25]:
data_eng[0]

'in  johnson was awarded an american institute of architects gold medal in  he became the first recipient of the pritzker architecture prize the most prestigious international architectural award'

In [27]:
import pandas as pd
g=pd.read_csv('german1.csv')

In [28]:
g.head()

Unnamed: 0                                               Body
0           0                                                NaN
1           1  Ich bin begeistert von den STANDARD - Newslett...
2           2  ... Aber momentan funktioniert das Abmelden od...
3           3  Es ist ganz einfach nervend!\r\nVor kurzem hab...
4           4   und sie als mitarbeiter sind natuerlich objektiv

In [29]:
g1=g.drop('Unnamed: 0', axis=1)
g1.head()

Body
0                                                NaN
1  Ich bin begeistert von den STANDARD - Newslett...
2  ... Aber momentan funktioniert das Abmelden od...
3  Es ist ganz einfach nervend!\r\nVor kurzem hab...
4   und sie als mitarbeiter sind natuerlich objektiv

In [30]:
g1.shape

(5000, 1)

In [31]:
g2 = g1.dropna()

In [32]:
g2.head()

Body
1  Ich bin begeistert von den STANDARD - Newslett...
2  ... Aber momentan funktioniert das Abmelden od...
3  Es ist ganz einfach nervend!\r\nVor kurzem hab...
4   und sie als mitarbeiter sind natuerlich objektiv
5  ...ist dieser newsletterservice - und deshalb ...

In [33]:
import string
pun_dic = dict((ord(char),None) for char in string.punctuation)

In [34]:
data_ger = []
lang_ger = []
from nltk.tokenize import word_tokenize
import re
for i,line in g2.iterrows():
    line = line['Body']
    if len(line)!=0:
        line = line.lower()                  #Convert everything to lowercase
        line = re.sub(r"\d+", "", line)      # remove all digits
        line = line.translate(pun_dic)       #Replace all punctuators with None
        data_ger.append(line)                #Add the processed tokenized data to list
        lang_ger.append("German") 

In [35]:
len(data_ger[0])

287

In [36]:
from google.colab import files
files.upload()

Saving hindi.csv to hindi.csv


In [37]:
h=pd.read_csv('hindi.csv')
h.head()

Unnamed: 0                                               Text
0           0   आदि में परमेश्वर ने आकाश और पृथ्वी की सृष्टि की।
1           1  और पृथ्वी बेडौल और सुनसान पड़ी थी; और गहरे जल ...
2           2  तब परमेश्वर ने कहा, उजियाला हो: तो उजियाला हो ...
3           3  और परमेश्वर ने उजियाले को देखा कि अच्छा है; और...
4           4  और परमेश्वर ने उजियाले को दिन और अन्धियारे को ...

In [38]:
h1=h.drop('Unnamed: 0', axis=1)
h1.head()

Text
0   आदि में परमेश्वर ने आकाश और पृथ्वी की सृष्टि की।
1  और पृथ्वी बेडौल और सुनसान पड़ी थी; और गहरे जल ...
2  तब परमेश्वर ने कहा, उजियाला हो: तो उजियाला हो ...
3  और परमेश्वर ने उजियाले को देखा कि अच्छा है; और...
4  और परमेश्वर ने उजियाले को दिन और अन्धियारे को ...

In [39]:
h2=h1.dropna()
h2.shape

(31121, 1)

In [40]:
data_hin = []
lang_hin = []

In [41]:
for i,line in h2.iterrows():
    line = line['Text']
    if len(line)!=0:
        line = line.lower()                                 #Convert everything to lowercase
        line = re.sub(r"\d+", "", line)                     # remove all digits
        line = re.sub(r"[a-zA-Z]+", "", line)
        line = line.translate(pun_dic)                      #Replace all punctuators with None
        data_hin.append(line)                #Add the processed tokenized data to list
        lang_hin.append("Hindi")

In [42]:
data_hin[0]

'आदि में परमेश्वर ने आकाश और पृथ्वी की सृष्टि की।'

In [44]:
m=pd.read_csv('marathi.csv')
m.head()

Unnamed: 0                                           headline
0           0  सचिन तेंडुलकरने बाळासाहेबांच्या आठवणींना दिला ...
1           1  बहुजन वंचित आघाडीची पहिली यादी जाहीर, प्रकाश आ...
2           2  गृहमंत्रिपद हे पार्ट टाइम नाही, राजीनामा द्या,...
3           3                पुण्यात आघाडीचा पोपट पुन्हा जिवंत !
4           4  शरद पवार यांनी मिलिंद नार्वेकर यांच्या कानात क...

In [45]:
m1=m.drop('Unnamed: 0', axis=1)
m1.head()

headline
0  सचिन तेंडुलकरने बाळासाहेबांच्या आठवणींना दिला ...
1  बहुजन वंचित आघाडीची पहिली यादी जाहीर, प्रकाश आ...
2  गृहमंत्रिपद हे पार्ट टाइम नाही, राजीनामा द्या,...
3                पुण्यात आघाडीचा पोपट पुन्हा जिवंत !
4  शरद पवार यांनी मिलिंद नार्वेकर यांच्या कानात क...

In [46]:
m1.shape

(9673, 1)

In [47]:
m2=m1.dropna()
m2.head()

headline
0  सचिन तेंडुलकरने बाळासाहेबांच्या आठवणींना दिला ...
1  बहुजन वंचित आघाडीची पहिली यादी जाहीर, प्रकाश आ...
2  गृहमंत्रिपद हे पार्ट टाइम नाही, राजीनामा द्या,...
3                पुण्यात आघाडीचा पोपट पुन्हा जिवंत !
4  शरद पवार यांनी मिलिंद नार्वेकर यांच्या कानात क...

In [48]:
m2.shape

(9673, 1)

In [49]:
data_mar = []
lang_mar = []

In [50]:
for i,line in m2.iterrows():
    line = line['headline']
    if len(line)!=0:
        line = line.lower()                                 #Convert everything to lowercase
        line = re.sub(r"\d+", "", line)                     # remove all digits
        line = re.sub(r"[a-zA-Z]+", "", line)
        line = line.translate(pun_dic)                      #Replace all punctuators with None
        data_mar.append(line)                #Add the processed tokenized data to list
        lang_mar.append("Marathi")

In [51]:
data_mar[0]

'सचिन तेंडुलकरने बाळासाहेबांच्या आठवणींना दिला उजाळा'

In [52]:
df=pd.DataFrame({"Text": data_eng+data_ger+data_hin+data_mar,
                 "language": lang_eng+lang_ger+lang_hin+lang_mar})

In [53]:
df.head()

Text language
0  in  johnson was awarded an american institute ...  English
1  bussysaintgeorges has built its identity on a ...  English
2  minnesotas state parks are spread across the s...  English
3  nordahl road is a station served by north coun...  English
4  a talk by takis fotopoulos about the internati...  English

In [54]:
df.shape

(48789, 2)

In [55]:
dg=df.loc[df['language']=='German']

In [56]:
dg.head()

Text language
3225  ich bin begeistert von den standard  newslette...   German
3226   aber momentan funktioniert das abmelden oder ...   German
3227  es ist ganz einfach nervend\r\nvor kurzem habe...   German
3228   und sie als mitarbeiter sind natuerlich objektiv   German
3229  ist dieser newsletterservice  und deshalb wird...   German

In [57]:
dh=df.loc[df['language']=='Hindi']

In [58]:
dh.head()

Text language
7995   आदि में परमेश्वर ने आकाश और पृथ्वी की सृष्टि की।    Hindi
7996  और पृथ्वी बेडौल और सुनसान पड़ी थी और गहरे जल क...    Hindi
7997   तब परमेश्वर ने कहा उजियाला हो तो उजियाला हो गया।    Hindi
7998  और परमेश्वर ने उजियाले को देखा कि अच्छा है और ...    Hindi
7999  और परमेश्वर ने उजियाले को दिन और अन्धियारे को ...    Hindi

In [59]:
df.loc[df['language']=='Marathi']

Text language
39116  सचिन तेंडुलकरने बाळासाहेबांच्या आठवणींना दिला ...  Marathi
39117  बहुजन वंचित आघाडीची पहिली यादी जाहीर प्रकाश आं...  Marathi
39118  गृहमंत्रिपद हे पार्ट टाइम नाही राजीनामा द्या त...  Marathi
39119                 पुण्यात आघाडीचा पोपट पुन्हा जिवंत   Marathi
39120  शरद पवार यांनी मिलिंद नार्वेकर यांच्या कानात क...  Marathi
...                                                  ...      ...
48784  मतपत्रिकेव्दारे मतदान घेऊन संशय दूर करा  उद्धव...  Marathi
48785  राज ठाकरेंवर व्यंगचित्रातून पलटवार करण्याच्या ...  Marathi
48786                     राज्यभर रामनवमी उत्साहात साजरी  Marathi
48787                                  दिलखुलास ऐश्वर्या  Marathi
48788  प्रेमात  लाख उडवले अन् लग्नास नकार दिला म्हणून...  Marathi

[9673 rows x 2 columns]

In [60]:
x,y = df.iloc[:,0],df.iloc[:,1]

In [61]:
x

0        in  johnson was awarded an american institute ...
1        bussysaintgeorges has built its identity on a ...
2        minnesotas state parks are spread across the s...
3        nordahl road is a station served by north coun...
4        a talk by takis fotopoulos about the internati...
                               ...                        
48784    मतपत्रिकेव्दारे मतदान घेऊन संशय दूर करा  उद्धव...
48785    राज ठाकरेंवर व्यंगचित्रातून पलटवार करण्याच्या ...
48786                       राज्यभर रामनवमी उत्साहात साजरी
48787                                    दिलखुलास ऐश्वर्या
48788    प्रेमात  लाख उडवले अन् लग्नास नकार दिला म्हणून...
Name: Text, Length: 48789, dtype: object

In [62]:
y

0        English
1        English
2        English
3        English
4        English
          ...   
48784    Marathi
48785    Marathi
48786    Marathi
48787    Marathi
48788    Marathi
Name: language, Length: 48789, dtype: object

In [63]:
from sklearn.model_selection import train_test_split

In [64]:
X_train,X_test,Y_train,Y_test= train_test_split(x,y,test_size=0.2,random_state=0)

In [65]:
X_train

19346    और आठवें दिन को उन्होंने महासभा की उन्होंने वे...
43983    नागपूरमध्ये डॉक्टर पत्नीनेच केला डॉक्टर पतीचा खून
12821     फिर अपना पूरबी सिवाना हसरेनान से शपाम तक बान्धना
48356    व्हायरल व्हिडिओ  काय खरंच मुंबई इंडियन्स हरल्य...
30408    और शूरवीरों में जो अधिक वीर हो वह भी उस दिन नं...
                               ...                        
21243    इसलिये कि उसके मुंह पर चिकनाईं छा गई है और उसक...
45891           पवारांच्या खेळीने आमदार कर्डिले धर्मसंकटात
42613       यंदाच्या हंगमात हे नवीन इतिहास रचणार धोनी र...
43567    क्षणात वडिलांपासून दुरावली मुलगी अपघातात डोक्य...
2732      johnny oconnor is determined to make a big im...
Name: Text, Length: 39031, dtype: object

In [66]:
X_test

12008    फिर दानियों की छावनी जो सब छावनियों के पीछे थी...
10629    फिर उसने बबूल की लकड़ी की होमवेदी भी बनाई उसकी...
19724    परन्तु परमेश्वर के एक जन ने उसके पास आकर कहा ह...
42418    खासदार चंद्रकांत खैरे यांच्याविरोधात अजामीनपात...
20826    एस्तेर ने उत्तर दिया है कि वह विरोधी और शत्रु ...
                               ...                        
34374    फरीसियों ने लोगों को उसके विषय में ये बातें चु...
12829    और देश को बांटने के लिये एक एक गोत्र का एक एक ...
38886    तब मुझ से यह कहा गया कि तुझे बहुत से लोगों और ...
40902                जीएसटी विधेयक विधानसभेत एकमताने मंजूर
35682    और चेलों को पाकर हम वहां सात दिन तक रहे उन्हों...
Name: Text, Length: 9758, dtype: object

In [67]:
Y_train

19346      Hindi
43983    Marathi
12821      Hindi
48356    Marathi
30408      Hindi
          ...   
21243      Hindi
45891    Marathi
42613    Marathi
43567    Marathi
2732     English
Name: language, Length: 39031, dtype: object

In [68]:
Y_test

12008      Hindi
10629      Hindi
19724      Hindi
42418    Marathi
20826      Hindi
          ...   
34374      Hindi
12829      Hindi
38886      Hindi
40902    Marathi
35682      Hindi
Name: language, Length: 9758, dtype: object

In [69]:
from sklearn.feature_extraction.text import TfidfVectorizer as tfidf

In [70]:
vectorizer = tfidf(ngram_range=(1,3),analyzer='char')

In [71]:
from sklearn import feature_extraction
from sklearn import metrics
vectorizer = tfidf(ngram_range=(1,3),analyzer='char')

In [72]:
from sklearn import linear_model
from sklearn import pipeline

In [73]:
pipeline_lr_model = pipeline.Pipeline([('vectorizer',vectorizer),('clf',linear_model.LogisticRegression())])

In [74]:
pipeline_lr_model.fit(X_train,Y_train)

Pipeline(memory=None,
         steps=[('vectorizer',
                 TfidfVectorizer(analyzer='char', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 3), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('clf',
                 LogisticRegression(C=1.0, class_weight=None, dual=False,
                                    fit_intercept=True, intercept_sc

In [75]:
y_predict = pipeline_lr_model.predict(X_test)

In [76]:
acc = metrics.accuracy_score(Y_test, y_predict)
print("Accuracy = ", acc*100)

Accuracy =  99.71305595408894


In [77]:
def lang_detect(text):
    text = " ".join(text.split())
    text = text.lower()
    text = re.sub(r"\d+", "", text)
    text = text.translate(pun_dic)
    pred = pipeline_lr_model.predict([text])
    return pred[0]

In [78]:
lang_detect("Hello how are you. This is in English")

'English'

In [79]:
lang_detect("Hallo, wie geht es dir, das ist auf Deutsch")

'German'

In [80]:
lang_detect("हेलो कैसे हो आप, ये है हिंदी में")

'Hindi'

In [81]:
lang_detect("नमस्कार कसे आहात, हे मराठीत आहे")

'Marathi'

In [82]:
cf = metrics.confusion_matrix(Y_test, y_predict)
print(cf)

[[ 629    0    0    0]
 [   1  942    0    5]
 [   0    0 6197   15]
 [   0    0    7 1962]]


In [83]:
lang_detect("आप कैसे हैं")

'Hindi'

In [84]:
lang_detect("wie gehts")

'German'

In [85]:
lang_detect("तू कसा आहेस")

'Marathi'

In [86]:
lang_detect("how long have i played in one sitting from morning till the early hours of the next day the birds were singing out side and i had to hobble to the bath room cos my bladder was so full i was in pain i would hardly eat perhaps some toast smoke endlessly and drink now thankfully the fascination has worn off and i have a girlfriend but still no job for the most part online gaming give me an adiction to illusory achievement and as there is no end in sight you keep going for the mirage of the ultimate  obsessive behaviour is of course always cause for concern but it always bothers me when articles about gaming talk in terms of reality obviously somebody who spends thirty hours a week playing everquest has a problem this problem however has nothing to do with a dysfunctional sense of reality an obsessive eq player does not consider the game to be real any more than  for example  an obsessive automotive tinkerer considers their car to be human if mmorpgs have a unique danger in terms of encouraging obsessive behaviour it is not that they create an absorbing virtual world but rather that they can be easily accessed  the problem here does not lie with the nature of gaming but with the nature of modern  hour culture  the problem with these so called mmorpgs is that you can never really complete them theres always another quest to do a few of my friends have only had about  hours sleep since it was released friday  championship manager consumed my life for years one particular session started at about pm on a sunday paused for a brief sleep at am on the monday ")

'English'

In [90]:
import pickle

In [91]:
ModelFile = open("ModelFile.pckl", 'wb')

In [92]:
pickle.dump(pipeline_lr_model, ModelFile)

In [93]:
ModelFile.close()